POST http://localhost:4000/api/v1/users/signup
Content-Type: application/json

{
    "apellidos": "diaz",
    "nombres": "juan",
    "fechanac": "2021-10-10",
    "sexo": 1,
    "doc": 2,
    "estciv": 3,
    "carfam": 2,
    "numhij": 4,
    "direccion": "Av. Arequipa",
    "distrito": "San Isidro",
    "dpto": "Lima",
    "refdir": "No",
    "tlf": "9876543",
    "cel": "987654123",
    "email": "hola@aaa.com",
    "gradoins": 4,
    "cargo": 2,
    "idsucursal": 3,
    "usuario": "prueba",
    "password": "prueba",
    "idestado": 2,
    "fecha_registro": "2021-10-10",
    "fecha_baja": "2021-10-10",
    "id_cartera": 10
}